### ISSUE TITLE
Draft Findings

### ISSUE THREAD

**Issue by F-said** [tsbarry/The-Economy-and-YOU#11]
Within your README's, draft the results of your CDA for all datasets. This includes:

* Distributions
* Relationships
* Models

This issue is defined as done when you have inserted all listed visualizations and included a rough (but succinct) discussion of your findings

**Comment by F-said** [comment]
@Themikster1 Add in following text to README 


### Draft Findings

After completing your `EDA`, draft your observations in a your README and detail what information you've gleaned from your visual analysis. Be sure to include visualizations, but do not use more than 5 graphs. This document must describe the following sections listed below.

Please ensure that this discussion is well-edited and concise. Think of this as a formal report that multiple individuals will utilize for business decisions. Do NOT include the place-holder text below.

> ### Distributions
> (place-holder text) What distributions did you notice throughout your EDA? Were any
> attributes normally distributed? If not, what methods can you take to force normality?
> 
> ### Relationships
> (place-holder text) What interesting metrics did you glean from your EDA? Did any box-plots, confidence intervals, or scatter plots
> appear to model significant relationships? 
>
> ### Models
> (place-holder text) What models did you use and why? What outcomes did your model predict? What might this hint about the relationship of your data?

**Comment by F-said** [comment]
https://www.markdownguide.org/basic-syntax/

**Comment by arimartorano** [comment]
Thierno was able to complete this task! Great job Thierno!
