### ISSUE TITLE
Implement dashboarding

### ISSUE THREAD

**Issue by F-said** [tsbarry/The-Economy-and-YOU#13]
Related to #12

After completing template, it should be implemented via tableau or streamlit

Definition of done: tableau (or streamlit) app implemented using template plan. Published as public page.

**Comment by F-said** [comment]
@Themikster1

**Comment by arimartorano** [comment]
Started building dashboard today. Will submit changes by tomorrow EOD, but we have started building our dashboard and have about 3 sheets ready to merge to the dashboard.
