### ISSUE TITLE
Complete presentation

### ISSUE THREAD

**Issue by F-said** [tsbarry/The-Economy-and-YOU#15]
Related to #14

Using the template slides that were developed, we should implement  presentation and ensure that each team member has a speaking role.

Definition of done: Presentation complete and timing planned out.

All slides should be signed off by group members, and every member of the team needs to be collaborating.

**Comment by F-said** [comment]
@Themikster1

**Comment by arimartorano** [comment]
Presentation slides are ready. Thierno and I are aware of our scripts and visuals!
