### ISSUE TITLE
Average should be recalculated

### ISSUE THREAD

**Issue by F-said** [tsbarry/The-Economy-and-YOU#17]
**Problem**

Average appears to be miscalculated 

```
(56000 + 102000)/2 = 79000
```

![image](https://github.com/tsbarry/The-Economy-and-YOU/assets/26397102/b861a7a4-c416-4b9c-9b10-057b070a3d39)

**Expected Output**

Rows should reflect accurate vals.

**Definition of done**

* changes committed and pushed
* db updated in schema
* ML model uses this new data

**Comment by tsbarry** [comment]
fixed it, i will run it in all the files so the change appears

**Comment by tsbarry** [comment]
complete
