### ISSUE TITLE
Fix dupes in state db

### ISSUE THREAD

**Issue by F-said** [tsbarry/The-Economy-and-YOU#7]
Currently, we have some duplicate state names in our state relation.

We should fix this in our data engineering pipeline, and recreate the relation on our database.

Example: New York is listed multiple times. This is probably because there are multiple companies that have headquarters in NY.

![image](https://github.com/tsbarry/The-Economy-and-YOU/assets/26397102/183e9f44-17fb-459a-a159-22124712505a)

**Comment by F-said** [comment]
1) Remove the city column and keep only unique states

OR

2) turn this table into a "city" table and only keep unique cities with their state names

**Comment by F-said** [comment]
@Themikster1

**Comment by arimartorano** [comment]
<3
