### ISSUE TITLE
Nulls in job db

### ISSUE THREAD

**Issue by F-said** [tsbarry/The-Economy-and-YOU#8]
Currently, the foreign key company_id and state_id are all nulled out. In addition, the "easy apply" column contains some nulls. These should be filled as we have both state & company column info for all tuples.

![image](https://github.com/tsbarry/The-Economy-and-YOU/assets/26397102/3272a275-78f8-4bd4-961d-256ca3e4d8fc)

**Comment by tsbarry** [comment]
fixed and complete
